version: '3.8'

services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PB_VERSION: 0.22.20
    container_name: sheep-land-pb
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      # Admin credentials (only used on first run)
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@sheep.land}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme123}
      
      # PocketBase configuration
      - PB_PORT=8090
      - PB_DATA_DIR=/pb/pb_data
      - PB_PUBLIC_DIR=/pb/pb_public
      - PB_MIGRATIONS_DIR=/pb/pb_migrations
      - PB_HOOKS_DIR=/pb/pb_hooks
      
      # Optional: Set memory limits
      - GOMEMLIMIT=900MiB
      - GOGC=100
    volumes:
      # Persistent data
      - pb_data:/pb/pb_data
      
      # For development: mount source directories
      # - ./public:/pb/pb_public:ro
      # - ./pb_migrations:/pb/pb_migrations:ro
      # - ./pb_hooks:/pb/pb_hooks:ro
    networks:
      - sheep-land-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: sheep-land-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_cache:/var/cache/nginx
    depends_on:
      - pocketbase
    networks:
      - sheep-land-network

volumes:
  pb_data:
    driver: local
  nginx_cache:
    driver: local

networks:
  sheep-land-network:
    driver: bridge