migrate((db) => {
  const collection = new Collection({
    "id": "_pb_livestock_options_id_", // Will be auto-generated by PocketBase
    "name": "livestock_options",
    "type": "base",
    "system": false,
    "schema": [
      {
        "system": false,
        "id": "lo_type_key",      // Field IDs are local to the migration definition
        "name": "type_key",
        "type": "text",
        "required": true,
        "unique": true,
        "options": { "min": 2, "max": 50, "pattern": "" }
      },
      {
        "system": false, "id": "lo_name_en", "name": "name_en", "type": "text", "required": true, "options": {}
      },
      {
        "system": false, "id": "lo_name_ar", "name": "name_ar", "type": "text", "required": true, "options": {}
      },
      {
        "system": false, "id": "lo_desc_en", "name": "description_en", "type": "text", "required": false, "options": {}
      },
      {
        "system": false, "id": "lo_desc_ar", "name": "description_ar", "type": "text", "required": false, "options": {}
      },
      {
        "system": false, "id": "lo_image", "name": "image", "type": "file", "required": false,
        "options": { "maxSelect": 1, "maxSize": 5242880, "mimeTypes": ["image/jpeg", "image/png", "image/webp", "image/gif"], "thumbs": ["100x100f", "300x300f"], "protected": false }
      },
      {
        "system": false, "id": "lo_badge_en", "name": "badge_en", "type": "text", "required": false, "options": {}
      },
      {
        "system": false, "id": "lo_badge_ar", "name": "badge_ar", "type": "text", "required": false, "options": {}
      },
      {
        "system": false, "id": "lo_weights_prices", "name": "weights_prices", "type": "json", "required": true, "options": {}
      },
      {
        "system": false, "id": "lo_is_globally_active", "name": "is_globally_active", "type": "bool", "required": false, "options": {"defaultValue": true}
      },
      {
        "system": false, "id": "lo_sort_order", "name": "sort_order", "type": "number", "required": false, "options": {}
      }
    ],
    "indexes": [
      "CREATE UNIQUE INDEX `idx_livestock_type_key` ON `livestock_options` (`type_key`)"
    ],
    "listRule": "@everyone",
    "viewRule": "@everyone",
    "createRule": "@admin",
    "updateRule": "@admin",
    "deleteRule": "@admin"
  });

  return Dao(db).saveCollection(collection);
}, (db) => {
  // To revert this migration (optional, but good practice)
  const dao = new Dao(db);
  const collection = dao.findCollectionByNameOrId("livestock_options");
  return dao.deleteCollection(collection);
})